### ISSUE TITLE
Product english fixes

### ISSUE THREAD

**Issue by Nebulis** [jlandure/techio-carpaccio-programming#2]
to sell our product => to sell our products
2-letter state code => 2-letters state code

Give a discount base on the total price, add state tax based on the state and the discounted price. =>
Give a discount based on the total price and dont forget to add the tax 'to the discounted price depending on the state tax rate

Here is the table of tax/discount rate => I think that I'would add an s to rate 🤔

**Comment by jlandure** [comment]
seems to be more 2-letter than 2-letters
=> https://www.google.fr/search?q="2-letter+state+code"
